### ISSUE TITLE
Licence for check_borg?

### ISSUE THREAD

**Issue by elmarx** [bebehei/nagios-plugin-check_borg#1]
Hi,

First of all, thanks for your work and for sharing this plugin.

I've made a couple of changes to make this script work under FreeBSD, but noticed that there's no licence along your code clarifying what I may do with your code and what not. :)

So I'd like to ask you kindly to add a licence to this repository.

**Comment by bebehei** [comment]
Hey @zauberpony, thanks for your interest in this little script. I have actually no experience what license fits best.

What License do you recommend? (a.k.a: Which license fits best for you?)

**Comment by elmarx** [comment]
Hm, as the other monitoring-plugins are [GPL licenced](https://github.com/monitoring-plugins/monitoring-plugins/blob/master/COPYING), that's the licence I'd go for.

**Comment by bebehei** [comment]
@zauberpony I've added the GPL license. Thank you for mentioning this topic.
