### ISSUE TITLE
FormattingError  on date

### ISSUE THREAD

**Issue by arthurzenika** [bebehei/nagios-plugin-check_borg#3]
```
# ./check_borg -R /data/backups/borg/
Formatting Error: "{time}{NUL}".format({'utcnow': datetime.datetime(2018, 1, 2, 15, 45, 44, 95787), 'user': 'root', 'borgpatch': '1.0.9', 'now': datetime.datetime(2018, 1, 2, 16, 45, 44, 95767), 'hostname': 'prod-web2', 'fqdn': 'prod-web2', 'pid': 4005, 'borgversion': '1.0.9', 'borgmajor': '1', 'borgminor': '1.0'}): KeyError('time')
date: invalid date '@'
```

It seems that now borg uses   --list-format LISTFORMAT not --format

**Comment by bebehei** [comment]
Hi @arthurlogilab Thank you for the bugreport.

It's unfortunate to say, but it seems, that `check_borg` does not support borg version 1.0 (anymore?).

That's interesting. I don't even understand why this happens. I have initially developed this script in combination with borg 1.0.x. I'm not able to trace back, what has actually changed.

Are you able to upgrade to 1.1.4?

**Comment by arthurzenika** [comment]
Am using borgbackup from official debian jessie-backport package on jessie. Stretch (current stable) is also on 1.0.9 https://packages.debian.org/search?keywords=borgbackup

```
ii  borgbackup              1.0.9-1~bpo8+1   amd64            deduplicating and compressing backup program
```

I will try to backport the buster package to jessie and stretch, but I guess it would be useful to have older versions working for this script too...

**Comment by bebehei** [comment]
> I will try to backport the buster package to jessie and stretch, but I guess it would be useful to have older versions working for this script too...

I fully agree with you. I'd like to have it working on 1.0, too. But my current guess, is that `borg list --(list-)format` doesn't work in general on the current 1.0 releases. I'm currently chatting with the maintainer of borgbackup.

**Comment by bebehei** [comment]
And it turns out, that `borg list` can't display/format the archive list. This "feature" came with the new borg 1.1. This is bogus for me.
