### ISSUE TITLE
borg env vars

### ISSUE THREAD

**Issue by z3dm4n** [bebehei/nagios-plugin-check_borg#5]
Hi there!

Thanks for your contribution. Great script. Exactly what I was looking for, but I think borg's env variables like BORG_PASSPHRASE and BORG_REPO should be included in check_borg and not in any insecure nagios/icinga file, because this files are usually readable by the unprivileged nagios/icinga user and therefore a potential security issue.  

My fix for this issue is to change permissions to 0700 on check_borg and execute check_borg via sudo by allowing the nagios user (in my case) to remotely execute this plugin via nrpe. 

BORG_PASSPHRASE and BORG_REPO are exported in check_borg directly. Would be nice, if check_borg wouldn't insist on the -R switch, if BORG_REPO is set.

**Comment by bebehei** [comment]
Am I right, that it would suffice to support a flag `--config`, which specifies a file, which gets sourced to set the `BORG_REPO` and `BORG_PASSPHRASE`?

**Comment by z3dm4n** [comment]
There are several different ways of fixing this. I am not sure which way is the best way. I like to keep things simple (KISS). So my temporary fix for this issue was to set 

```bash
export BORG_PASSPHRASE='secret'
export BORG_REPO='ssh://user@host.tld:port/./repo'
```
inside check_borg and to use this var if there is no repo specified by using `-R repo`:

```bash
# check if env var $BORG_REPO is set
if [ -n "${BORG_REPO}" ]; then
    repo=${BORG_REPO}
fi                          
```
