### ISSUE TITLE
date command

### ISSUE THREAD

**Issue by z3dm4n** [bebehei/nagios-plugin-check_borg#7]
Hi there... again! ;-)

It seems that [GNU](http://man7.org/linux/man-pages/man1/date.1.html) `date` gives a f*** about POSIX compatibility. I would like to run check_borg on my FreeBSD boxes as well, but [*BSD]( https://www.freebsd.org/cgi/man.cgi?query=date&apropos=0&sektion=0&manpath=FreeBSD+11.1-RELEASE+and+Ports&arch=default&format=html) `date` doesn't like the `--date` switch of GNU `date`.

The date command confuses me at the moment. I need to look deeper inside your code to fix the issue. Maybe you can give me a little hint on how to fix this for *BSD. 

[Differences between both commands](https://www.cyberciti.biz/faq/linux-unix-formatting-dates-for-display/)

Thanks a lot!

**Comment by bebehei** [comment]
Ouch. FreeBSD has a `-v` switch, which does almost the same as `--date`. [But neither `-v` nor `--date` are a POSIX standard](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/date.html).

**Comment by bebehei** [comment]
[I'm vomiting, when reading the proper answer on Stackexchange](https://unix.stackexchange.com/a/4589).

To elaborate the use a bit more: We need the date command just to convert dates. borg gives out normal dates and also we only require relative readable dates from the user input. GNU date is awesome, as it can suck in almost every date value and spit it out the required date in the given format.

Are you able to install GNU coreutils on your system? I'm not that experienced on *BSD systems, but it looks like there is a [freshport for this](https://www.freshports.org/sysutils/coreutils/). If it is installable as a supplement, I'd kindly request you to install this.

**Comment by z3dm4n** [comment]
`-v` looks quite interesting. This could fix the problem. Installing GNU coreutils would fix the problem as well and is much easier. Seems like there is no way to bring both `date` commands to do the job on both platforms with there own utils without blowing the code up quite a lot. :-( Consider this issue as closed. I'll install gdate and do `:%s/date/gdate/g` and this should do the trick as well. If not, I'll let you know.

**Comment by bebehei** [comment]
@z3dm4n I've created #8 reflecting the necessary changes to support a `DATE` variable. If you could test it, I'd appreciate it.
